import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
//import "@radix-ui/themes/styles.css";
//import { Theme } from "@radix-ui/themes";
//import "@radix-ui/themes/layout.css";
import Head from 'next/head'

import data from '@/data/portfolio.json'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Benoît Guchet",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
    <head>
      <link
                        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap"
                        rel="stylesheet"
                      />
    </head>
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <NavBar></NavBar>
            {children}
      </body>
    </html>

  );
}
