import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
//import "@radix-ui/themes/styles.css";
//import { Theme } from "@radix-ui/themes";
//import "@radix-ui/themes/layout.css";
import Head from 'next/head'

import data from '@/data/portfolio.json'
import {getAllData} from "@/lib/getData";
import {I18nProviderClient} from '@/locales/client'

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
      default: "Benoît Guchet",
      absolute: "",
      template: "%s | Full-stack freelance developer – Symfony / Vanilla JS | Benoît Guchet"
  },
  description: "Generated by create next app",
};

export default async function RootLayout({params, children}:
    Readonly<{ params: Promise<{ locale: string }>, children: React.ReactNode;}>)
{
    const {locale} = await params;
    return (
            <html lang={locale}>
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@100..800&display=swap"
                      rel="stylesheet"/>

                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap"
                    rel="stylesheet"
                />
                <link type="image/png" sizes="16x16" rel="icon"
                      href={'/icons8-brackets-external-basicons-solid-edtgraphics-16.png'}/>
                <link type="image/png" sizes="32x32" rel="icon"
                      href={'/icons8-brackets-external-basicons-solid-edtgraphics-32.png'}/>
                <link type="image/png" sizes="96x96" rel="icon"
                      href={'/icons8-brackets-external-basicons-solid-edtgraphics-96.png'}/>
                <link type="image/png" sizes="72x72" rel="icon"
                      href={'/icons8-brackets-external-basicons-solid-edtgraphics-72.png'}/>
                <link type="image/png" sizes="96x96" rel="icon"
                      href={'/icons8-brackets-external-basicons-solid-edtgraphics-96.png'}/>
            </head>

            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            <I18nProviderClient locale={locale}>
                <NavBar data={getAllData()}></NavBar>
                {children}
            </I18nProviderClient>
            </body>
            </html>

    );
}
